### ISSUE TITLE
List compute examples fail

### ISSUE THREAD

**Issue by mchlumsky** [dtantsur/rust-openstack#98]
list-keypairs.rs and list-servers.rs from examples directory don't seem to work.
All the other list-*.rs examples work fine.

I get this error when running list-servers.rs (and the same error when running list-keypairs.rs):
```
$ RUST_BACKTRACE=full cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.09s
     Running `target/debug/openstack`
thread 'main' panicked at 'Cannot list servers: Error { kind: EndpointNotFound, message: "Endpoint for service compute was not found", status: None }', src/libcore/result.rs:999:5
stack backtrace:
   0:     0x55caf003e1fb - std::panicking::default_hook::{{closure}}::ha6347d45d6ce78e6
   1:     0x55caf003ded7 - std::panicking::default_hook::h710ef7fef9effc11
   2:     0x55caf003e970 - std::panicking::rust_panic_with_hook::h76ef5746177cf2f1
   3:     0x55caf003e4f2 - std::panicking::continue_panic_fmt::h1bc636947a39411e
   4:     0x55caf003e3d6 - rust_begin_unwind
   5:     0x55caf0056a3d - core::panicking::panic_fmt::h1858cc192bbf4d30
   6:     0x55caef5a4ea3 - core::result::unwrap_failed::hfff6da115b3fa5b4
                               at /builddir/build/BUILD/rustc-1.37.0-src/src/libcore/macros.rs:18
   7:     0x55caef5a51fa - core::result::Result<T,E>::expect::he640bb0f24fc5474
                               at /builddir/build/BUILD/rustc-1.37.0-src/src/libcore/result.rs:827
   8:     0x55caef5a4690 - openstack::main::h0508d5cdcc1d742d
                               at src/main.rs:29
   9:     0x55caef5a5c40 - std::rt::lang_start::{{closure}}::hda5be38dd52a3df8
                               at /builddir/build/BUILD/rustc-1.37.0-src/src/libstd/rt.rs:64
  10:     0x55caf003e373 - std::panicking::try::do_call::h0ad313ed04aaa877
  11:     0x55caf0041fba - __rust_maybe_catch_panic
  12:     0x55caf003ef3d - std::rt::lang_start_internal::h1765bcf229d6c7c6
  13:     0x55caef5a5c19 - std::rt::lang_start::he071acc26c4d85b0
                               at /builddir/build/BUILD/rustc-1.37.0-src/src/libstd/rt.rs:64
  14:     0x55caef5a4cfa - main
  15:     0x7fcb2be3ff33 - __libc_start_main
  16:     0x55caef5a223e - _start
  17:                0x0 - <unknown>
```
My service catalog seems fine. It works with the openstack CLI.
```
$ openstack endpoint list --service compute
+----------------------------------+-------------------+--------------+--------------+---------+-----------+-------------------------------------------------------------------------+
| ID                               | Region            | Service Name | Service Type | Enabled | Interface | URL                                                                     |
+----------------------------------+-------------------+--------------+--------------+---------+-----------+-------------------------------------------------------------------------+
| a6c52b6a89d346d585f4aa2e761a02d2 | <redacted> | nova         | compute      | True    | internal  | http://<redacted>:8774/v2.1/%(tenant_id)s                           |
| b23551a517c949a18f90eb9ec08caaac | <redacted> | nova         | compute      | True    | admin     | https://<redacted>:8774/v2.1/%(tenant_id)s                          |
| df71538ee05542df9dbcbaf6cc5e512d | <redacted> | nova         | compute      | True    | public    | https://<redacted>:8774/v2.1/%(tenant_id)s |
+----------------------------------+-------------------+--------------+--------------+---------+-----------+-------------------------------------------------------------------------+
```

My cargo.toml:
```$ cat Cargo.toml 
[package]
name = "openstack"
version = "0.1.0"
authors = ["Martin Chlumsky <martin.chlumsky@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["compute", "image", "network"]
compute = []
image = []
network = []


[dependencies]
openstack = "0.3.0"
waiter = "0.1.1"
fallible-iterator = "0.2.0"
env_logger = "0.6.0"
```
Thank you!

**Comment by mchlumsky** [comment]
Actually this appears to be a problem in the osauth crate.
I get the same error when I try this example:
https://github.com/dtantsur/rust-osauth/blob/master/examples/list-servers.rs

**Comment by mchlumsky** [comment]
This is fixed by https://github.com/dtantsur/rust-osauth/commit/d14de64fd906a6e2b11db3e478b2023d3d2a8802

Sorry for all the noise. I'll just compile against master of rust-osauth until you cut a new release for rust-osauth.

Thanks!
